application: partysenseapp
version: 1
runtime: python27
api_version: 1
threadsafe: true

env_variables:
   TMP: C:\Users\robert\AppData\Local\Temp

handlers:
- url: /(.*.txt)
  static_files: stylesheets/\1
  upload: stylesheets/(.*.txt)

- url: /admin.*
  script: main.app
  login: admin

- url: /club-manager.*
  script: main.app
  login: admin

- url: /stylesheets
  static_dir: stylesheets

- url: /scripts
  static_dir: scripts

- url: /images
  static_dir: images

- url: /scripts
  static_dir: scripts

- url: /.*
  script: main.app

builtins:
- remote_api: on

libraries:
- name: jinja2
  version: latest